### ISSUE TITLE
Success alerts should not be orange

### ISSUE THREAD

**Issue by kyledrake** [neocities/neocities#160]
They should be green. Alerts should be yellow or orange, and alerts should be red.

**Comment by violasong** [comment]
Ok, looks like the classes that need to be used are alert-error and alert-success in addition to alert-block, but a bunch of elements are just "alert" (and it seems some of those are doing double-duty for both errors and successes?). For now I've made a change that should make it so that alert-success is green, but I'm leaving the generic alert ones for now. I can do more if you tell me an easy way to test both alert types.

**Comment by kyledrake** [comment]
Thanks, I'll try to fix them.
