### ISSUE TITLE
Deletes & Updates DELAY [approx 0.5 hour]

### ISSUE THREAD

**Issue by fionnachan** [neocities/neocities#182]
- Deleted some .js .css and .html on Dashboard, but the links are still accessible.
  [Page deleted]
  ![fullpage](https://cloud.githubusercontent.com/assets/13184582/8818273/ea04b550-3071-11e5-8b4f-a2f273581c5d.png)
- Updated the index.html but the "http://xxx.neocities.org/" is different from the "http://xxx.neocities.org/index.html" 
  i.e. "http://xxx.neocities.org/" still looks like the previous version
  ![strange](https://cloud.githubusercontent.com/assets/13184582/8818276/ed60aede-3071-11e5-824f-75b82e5b8cc5.png)
  ![index](https://cloud.githubusercontent.com/assets/13184582/8818259/c1af432c-3071-11e5-9019-081bf18d397a.png)

*Update seems to take 0.5-1 hour

**Comment by kyledrake** [comment]
Could you try it now and see if it's still doing it? One of our proxy servers for our new CDN network just had a hiccup. I'm still trying to figure out what happened here.

**Comment by kyledrake** [comment]
I believe this is a bug related to the cache reset plugin and the current version of nginx we're using. I'm going to try updating nginx and see if it resolves this issue.

**Comment by fionnachan** [comment]
It's alright now.
The issue started ytd or 2 days before, but the delay wasn't as long.

Thanks.

**Comment by kyledrake** [comment]
@fionnachan Yeah, the cache reset is supposed to happen within 5 seconds, and it usually does. Except sometimes we get a weird '500' error in our proxy servers that isn't recorded in the logs, but eventually it finally does work. I'm updating the proxy to a newer version to see if it clears this up. If not, we might have to turn off the caching for now. I haven't announced this yet because I'm testing to make sure there aren't any issues before making it permanent.

**Comment by kyledrake** [comment]
So, this isn't a single bug per-se. We have global CDN that serves content and caches it regionally so sites load fast. Sometimes due to a server failure or something dumb, the cache purge can get delayed for up to half an hour.

I'm going to close this and simply say that, over the last 6 months, we've significantly improved the stability of this system, and we'll continue to find little bugs and issues here and there, and they get resolved. We're pretty close to a perfectly working system at this point. Give me a few more weeks here and we should be a lot better with this.

Thanks for chiming in!
