### ISSUE TITLE
Make this repository the parent repository

### ISSUE THREAD

**Issue by violasong** [neocities/neocities#20]
I think the reason why our check-ins to this project don't show up in our github contributions may be because this project is a fork.
https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/

I think we can fix this If we delete the original repository and specify this project as the parent. 
https://help.github.com/articles/what-happens-to-forks-when-a-repository-is-deleted-or-changes-visibility/

**Comment by kyledrake** [comment]
I noticed this too, thanks for figuring this out! I'm about to make some saurkraut, after that I will look into executing these changes.

**Comment by kyledrake** [comment]
Okay it looks like I just need to delete the old repo, and this one will automagically become the canonical repo. I think.

I'm going to do this tomorrow. The big problem is that I need to merge some of the issues filed on the original repo, because they have some useful information (such as https://github.com/kyledrake/neocities-web/issues/36)

**Comment by kyledrake** [comment]
Well that didn't work. I deleted the parent repo and now it's just saying we're forked from some random person's repo. I have no idea how to fix this.

**Comment by kyledrake** [comment]
I emailed Github support to see if they can do something about this.

If this continues to be dumb, I may propose to use Gitlab instead, since unlike Github, it's completely open source.

**Comment by kyledrake** [comment]
Github turned around really quickly. We're done!
