### ISSUE TITLE
Move repository to BitBucket/Gitgud.io/neetco.de instead of GitHub

### ISSUE THREAD

**Issue by videofindersTV** [neocities/neocities#206]
Ever since Business Insider published [this inside story about what is truly happening with GitHub](http://www.businessinsider.com/github-the-full-inside-story-2016-2) I've been concerned about the future of the NeoCities project. [Recently, Github has also been tinkering with other people's projects without consent](https://www.reddit.com/r/github/comments/43sfxp/why_are_there_little_neckbeard_icons_next_to_my/), and this could pose a huge potential problem for the NeoCities Project.

**I say that you should move the NeoCities project to BitBucket, Gitgud.io, neetco.de, or any other place that has Git hosting instead of GitHub.** It's for the better, for you **and** the NeoCities project.

**Comment by kyledrake** [comment]
Note: These are my opinions, not the opinions of other people working on Neocities.

I'm honestly not perfectly happy with Github right now either, *but for very different reasons that aren't mentioned in the article*. Note that this article's sources consist primarily of anonymous "disgruntled employees". Rake the muck hard enough and you can make any company look like it's about to blow up. I also know people that work at Github that enjoy working there. I also appreciate much of the work they're doing (the Electron work is incredibly important to the future of desktop software). Overall, Github's contribution to the open source community has been positive.

I've been pondering a move away from Github for a few reasons:

Their backend is closed source, and I want to send a message that Neocities prefers to support web portals that are open source. The fact that the open source community is heavily dependant on a closed source, proprietary backend is an elephant in the room we need to start talking about.

There's no good reason for Github's backend to remain closed source that isn't a logical fallacy. Open sourcing Neocities has significantly benefited us, while Github staying closed source has certainly not prevented people from making clones of Github (that are arguably better at this point). But what it has done is prevent transparency of their backend (thus eroding trust), and prevented users from contributing features to the backend. The [Dear Github](https://github.com/dear-github/dear-github) letter I think demonstrates how being closed source has retarded the development of Github over time, an observation not surprising to anyone that understands why open source is a superior way to develop *almost all* software. That said, the current functionality of Github is more than good enough for our needs.

Second, I'm disappointed that instead of remaining independent and community oriented, they went the liquidity event route when it simply wasn't necessary. That Faustian bargain has made them (and thus the entire open source community) dependent on greedy, politically dubious investors that don't have, in my opinion, our best interests in mind. For example, one of their investors is on record contributing large sums of money to a superPAC that created [trash like this](https://www.youtube.com/watch?v=pUcHSndDbqQ) as part of their ongoing quest to rip up anti-trust regulations so they can build a Standard Oil on top of the tech community.

As someone with deep previous experience on political campaigns, I share Lawrence Lessig's and the Bernie Sanders campaign's concerns about superPACs and I'm personally avoiding sending money to organizations that have investors with ties to them.

Lastly, there are numerous excellent, fully open source alternatives like [Gitlab](https://about.gitlab.com/) and [Gogs](https://gogs.io/). I wouldn't switch to another hosted provider, we would likely just run our own instance on a VPS we control.

That's my thought process for now. I'm not making a decision on this for at least a few months. There are far higher priority things we need to get to, and as a bootstrapped startup, we need to use our limited time economically.

**Comment by rugk** [comment]
BTW instead of Gogs you may consider the fork [GitTea](https://gitea.io) (which is  - in contrast to Gogs - community-managed).

**Comment by kyledrake** [comment]
I'm going to close this ticket for now. We'll consider filing a ticket in the future to properly do this but it's really not on the priority list right now, we've got way too much stuff backlogged that needs to get worked on. Thanks for the input though!
