### ISSUE TITLE
Following yourself in surf mode

### ISSUE THREAD

**Issue by DrEvilBrain** [neocities/neocities#215]
It's possible to follow yourself by going into surf mode just by clicking the follow button. Minor issue but I guess it matters?

[Example of myself following myself](https://neocities.org/site/syscomindustries)

**Comment by joppiesaus** [comment]
This is a lot harder now, but still possible.
The 
You need to figure out your site's ID. If you have another site or a friend's site this is quite easy; go to your site on the alternate site, inspect the "follow" button and you've

**Comment by joppiesaus** [comment]
This is a lot harder now, but still possible.
There is a function for this: `Site.toggleFollow(siteId, csrfToken)`
The `crsfToken` is included in the page. It's easy to get.
The `siteId` however... You need to figure out your site's ID. If you have another site or a friend's site this is quite easy; go to your site as the alternate site, inspect the "follow" button and you've got your `siteId`.
If you don't have this, you can figure it out by time. You can go to browse mode, sort by time(newest or oldest), and find your site. This is hard when you have a old site, but when you have a new one this is really easy. Find your site, go to it in surf mode. Go back one site, inspect the follow button, and see what id the site has. Write it down, go two sites further, and write that id down as well. If you're lucky, there's only one id in between that, that's your siteid. If not, you have to try them all. Now you can use the function, or in surf mode just `toggleFollow(yoursiteid)`.
There are probably more ways but these are the obvious ways that I found out.
A fix would be to check on the server if the `siteId` is not the site who's trying to follow. Also, I'd doubt if people actually do this because it's so difficult(it's not an issue if it isn't a problem).

I also noticed (while trying this) that if you go further then one page in browse mode, and you try to surf the website, you end up at a different website then you clicked on. This is because the `surf` function doesn't take the amount of pages you are in browse mode into account. (i.e. if you are in the second page of browse mode and you click the second site, it goes to the second site of the search criteria and not the amount of the pages already traveled + the selected site). The correct amount would be: `page * amountPerPage + siteOnPage`. Or just set it properly server-side. (Do I need to open a separate issue for this?)

I have a lot of trouble trying to explain this to you over the internet, but I hope this helps. I am going to try and fix these issues and then pull-request the fixes. :love_letter:
