### ISSUE TITLE
Prepare for Neocities announcement

### ISSUE THREAD

**Issue by kyledrake** [neocities/neocities#23]
We launched the major upgrade to Neocities, but have not yet made the big announcement.

Most of the things I wanted to do are completed, though I might want to fix the replication problem before we do.

@violasong I wanted to ping you for your list of changes you'd like to make before we do the announcement, so we can setup a task list (https://github.com/blog/1375%0A-task-lists-in-gfm-issues-pulls-comments) and be able to work on it.

**Comment by violasong** [comment]
- I really think the supporter page and homepage need a little design work to accommodate the new pricing concept. I haven't been feeling well though so having a hard time wrapping my head around this... will see how I'm doing tomorrow
- It would be really nice if we could improve the signup flow for those clicking on one of the paid plans. People who were mainly interested in donating rather than joining the site could be confused/irritated by being sent to /#new
- Final css edits to whole site

**Comment by violasong** [comment]
Re: Final CSS edits - Tomorrow I'll try to work on some of the little layout problems I noticed on mobile. The browse page looks especially bad. I need to find a better mobile browser emulator.

Awaiting further discussion with @kyledrake on pricing.

**Comment by violasong** [comment]
I've been working on CSS fixes for mobile. After I last pulled the latest changes I get an error when I try to run bundle: "You passed :source as an option for gem 'stripe', but it is invalid." What should my Gemfile entry for stripe look like?

**Comment by kyledrake** [comment]
ah, sorry, try upgrading bundler:

gem install bundler

**Comment by violasong** [comment]
That did it, thanks!

Still getting a 404 on /plan when logged in.

**Comment by kyledrake** [comment]
Waiting on a new front page splash before doing this.
