### ISSUE TITLE
ssl warnings for custom domains

### ISSUE THREAD

**Issue by substack** [neocities/neocities#234]
It seems that the ssl certificates for custom domains are for `*.domain` so for example [https://www.bits.coop](https://www.bits.coop) works but [https://bits.coop](https://bits.coop) throws up a scary warning.

**Comment by kyledrake** [comment]
That is really bizarre. It should be working fine:
https://github.com/neocities/neocities/blob/master/workers/lets_encrypt_worker.rb#L39

My fix here was to re-issue the certificate.

This is the output from when I just refreshed it from the script:
```
verifying accessability of test file on bits.coop
testing http://bits.coop/.well-known/acme-challenge/test30d7854b-1c05-4a0f-951a-32f3ec7e3c87
test succeeded, sending challenge request verification
bits.coop : valid
VALIDATED: bits.coop
verifying accessability of test file on www.bits.coop
testing http://www.bits.coop/.well-known/acme-challenge/test239bfd9d-dfd5-4928-9ad7-c682f8a255d5
test succeeded, sending challenge request verification
www.bits.coop : valid
VALIDATED: www.bits.coop
verified domains: ["bits.coop", "www.bits.coop"]
```

That should give you a flavor of the workflow - we need to validate for both and then forge that into a certificate after confirming we control it. The behavior right now is that if one of them fails, we just close on a certificate for the one that didn't fail. This is because a lot of sites choose to not put in the www.*, or only have that and skip the root domain, so by requiring both, we're increasing the chance of breakage.

This cert was refreshed on November 11th previously, and my theory is that one of the two domain validation checks failed for some technical reason, either on our end or on Let's Encrypt's. So our "compatibility mode" caused a failure here by ignoring a valid site failing to verify.

I'm going to need to think of a clever way to improve this, perhaps a retry later if only one verify succeeds.

Thanks for reporting this!

**Comment by joppiesaus** [comment]
I do not have this problem on Chrome 55.0.2883.59 (beta) & Firefox 40.0.3 on Windows.

**Comment by kyledrake** [comment]
@joppiesaus I may have just fixed it for you. But weirdly, it was working fine in Chrome but not in my `curl`. I'm more apt to believe the `curl` version of the story here, because it's stateless.

**Comment by asdf1337** [comment]
I became a supporter today and my site is also throwing an SSL error.
Firefox shows: SSL_ERROR_INTERNAL_ERROR_ALERT
Chrome shows: ERR_SSL_PROTOCOL_ERROR
domain is occult.info

**Comment by kyledrake** [comment]
@asdf1337 It should be working now. Right now it's a waiting game, where the registrar needs to update it's records, otherwise the letsencrypt fails. I'm going to work on improving this today.

**Comment by asdf1337** [comment]
thanks for the quick response! 
also for future reference, what is the technical support email address for neocities?

**Comment by kyledrake** [comment]
contact@neocities.org

**Comment by rugk** [comment]
https://bits.coop/ also works here, I see no issues. So I think you can close this issue.
