### ISSUE TITLE
Performance/TLS: support ChaCha20

### ISSUE THREAD

**Issue by rugk** [neocities/neocities#238]
See https://www.imperialviolet.org/2013/10/07/chacha20.html

At least on mobile devices without hardware AES support it is faster and also very secure.

support: http://caniuse.com/#feat=chacha20-poly1305

**Comment by kyledrake** [comment]
Oh fun, I didn't know chacha was available with openssl/nginx. I'll poke around and see if I can get it to work on our proxy servers, thanks for the suggestion!

**Comment by rugk** [comment]
Some help: https://scotthelme.co.uk/doing-the-chacha-with-nginx/

**Comment by kyledrake** [comment]
I've done a lot of research on this, and unfortunately I'm going to have to pass on this implementation.

The problem is that chacha20-poly1305 is only fast on certain devices (read: shitty mobile phones), and it's slower on everything that has the AES booster code (including many mobile phones). In order to fix that (by choosing based on client's CPU), as I understand it I can't just use a newer OpenSSL (which in itself would be a big hassle to use on our servers ATM), I have to instead use one of Cloudflare's C patches for OpenSSL, and we saw last week what happens when Cloudflare patches C to ROFLscale something.

It's just a little too bleeding edge for us ATM. But hopefully in the future this gets implemented in a structured way and client-cipher detection is just baked into the design.

Thanks for the idea! It was interesting to learn about this.
