### ISSUE TITLE
HTTPS/TLS issues

### ISSUE THREAD

**Issue by rugk** [neocities/neocities#239]
reference: scans [by](https://www.ssllabs.com/ssltest/analyze.html?d=rugk.neocities.org&s=2620%3a2%3a6000%3a0%3a0%3abad%3adab%3acafe&hideResults=on) [SSLLabs](https://www.ssllabs.com/ssltest/analyze.html?d=bits.coop&s=198.51.233.1&hideResults=on&latest):

* maybe performance impact: On subdomains you serve the root certificate (i.e. AddTrust External CA Root), which is unnecessary as it is already included in browsers, basically it only increases the handshake size
* cipher suites may be renewed following [Mozilla's recommendations](https://mozilla.github.io/server-side-tls/ssl-config-generator/) (I recommend "Modern")
* Performance impact: You do not support [OCSP stapling](https://www.digitalocean.com/community/tutorials/how-to-configure-ocsp-stapling-on-apache-and-nginx), in some Browsers (i.e. Firefox) it can have a performance issue as then the CA maybe queried for the revocation state of the cert
* Your HSTS header is too short (less than 180 days), if you configure this properly you'll get A+ on SSLLabs

**Comment by kyledrake** [comment]
Thanks! In order:

The root cert was just pulled.

We're basically using Moz's recommendations but without chacha20 (see other discussion).

OCSP is working for the root/subdomain cert, but it's currently not working for domains. This is due to the nginx lua code for getting OSCP cert having issues when doing dynamic loading. I'm not sure we will be getting to this for a very long time at this point.

HSTS has been set to long life and preload, is scheduled to be put in the browser HSTS lists.

**Comment by rugk** [comment]
AFAIK nginx should support OCSP stapling with multiple domains. I don't know what you mean with dynamic loading, but in case you just mean a reload of nginx - yes, you need to do a request to the domain afterwards, so nginx starts to fetch the certs.

FYI you can also get the needed OCSP stapling files "manually" via a shell script (& openssl) and let nginx use the file: https://community.letsencrypt.org/t/will-does-the-letsencrypt-client-create-a-cert-chain-usable-with-ocsp-stapling/2072/19

And nice you'll also preload… :smiley:

**Comment by kyledrake** [comment]
Once you get to the scale we're at, you need to start using lua to dynamic load SSL certs based on the Host coming in. We don't create virtualhosts for each domain, because at scale it will require us to reload nginx often and nginx will no longer be able to start in a reasonable amount of time.

Basically we need to get the code example in this to work, but it didn't work and I wasn't able to debug the reason why: https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/ocsp.md

**Comment by rugk** [comment]
Thanks for your explanation.
