### ISSUE TITLE
Strange redirect in IPFS gateway

### ISSUE THREAD

**Issue by RMBLRX** [neocities/neocities#250]
_I was going to comment this in #156 but didn't want to clutter the thread.  Anyhow, I noticed some strange behavior on one of my pages in your IPFS gateway:_

So I just nailed down a method of properly _relativizing_ URLs in Jekyll so that my site is portable across top-level domains and IPFS gateways alike, but if you investigate the link in the big logo, [here](http://ciqnhui5k5tfn73i63rykmatlctmfpvl4xwfohjynuhkwihr6jr3o6y.ipfs.neocitiesops.net/), it seems to redirect to this empty URL: http://ciqnhui5k5tfn73i63rykmatlctmfpvl4xwfohjynuhkwihr6jr3o6y.ipfs.neocitiesops.net/ipfs/QmcbVg9cZkg7hhj86ezepST3yZfpypCizpato1DyGpxDNa/stagingGrounds/

... instead of the [appropriate URL](http://ciqnhui5k5tfn73i63rykmatlctmfpvl4xwfohjynuhkwihr6jr3o6y.ipfs.neocitiesops.net/stagingGrounds/), which seems to be correct, not only in the page source and [neocities itself](https://rapidexpedition.neocities.org/), but also in [ipfs.io's own gateway](https://gateway.ipfs.io/ipfs/QmcbVg9cZkg7hhj86ezepST3yZfpypCizpato1DyGpxDNa/).

_(As an aside: why does my font seem to change on neocities' main site and gateway vs when hosted on [netlify](https://www.rapidexpedition.org/) or accessed through ipfs.io using the hash granted by neocities?  It might be some idiosyncrasy with my build I guess since, oddly enough, I get the exact same behavior on localhost.)_

**Comment by kyledrake** [comment]
My guess is it's because it's trying to load the subdomain and the path CID at the same time, which the gateway isn't really designed for. I'm going to be making changes to how this works in the near future so I'd prefer to start over with a better version than spend almost as much time figuring this one yet, so look for the new gateway in the future. Thank you for reporting!
