### ISSUE TITLE
oAuth support in API

### ISSUE THREAD

**Issue by thejeshgn** [neocities/neocities#251]
It would be great to have oAuth support in API so we don't have to share the credentials with tools. I think Neocities is a great platform for rebooting indie web and blogging. Please have a look at this [discussion](https://github.com/scripting/Scripting-News/issues/21/).

**Comment by joppiesaus** [comment]
Have you looked at an [API Key](https://neocities.org/api)(scroll down, it's on the bottom of the page)? I have no idea if this suits your situation, but it removes the need for user credentials.

**Comment by kyledrake** [comment]
I suppose this could be cool, but I'm not really feeling like getting crazy with oauth2 right now in my life. I'd rather people used email and password to login rather than bunching up their login dependencies on platforms. I think this makes more sense for stuff like Facebook and Twitter, not as much for Neocities.
