### ISSUE TITLE
Add view source code feature for personal websites

### ISSUE THREAD

**Issue by spaceywolfi** [neocities/neocities#256]
hey!
I think it would be cool to add a feature that allows people to see the source code of a website.
For example by navigating to /src of the currently view site.
:)

**Comment by Retroity** [comment]
You can view the source code of a page by right clicking and then clicking "View page source" on chrome and firefox. Unless you're referring to a source code browser like Github?

**Comment by spaceywolfi** [comment]
yes i am talking about a source code browser

**Comment by kyledrake** [comment]
I'm trying to keep the amount of "custom neocities http stuff" to a minimum here, just so that the sites will work as expected elsewhere too. I would rather people used the browser source code viewer for the sites themselves, it's far better than anything I could ever come up with.

Thank you for the idea!
