### ISSUE TITLE
[BUG] Style sheet and favicon files not linking right?

### ISSUE THREAD

**Issue by minegamer5570** [neocities/neocities#272]
I help some friends make sites with Neocities and made them all favicons and they work fine. I have made  a site which links all of the sites together. For some reason, the site won't use the Style sheet and favicon files even though they have the right address and do work if i look at them in the developer window in chrome. Any help please!

Site: https://thering.neocities.org/

**Comment by joppiesaus** [comment]
They seem to work for me! You might want to improve your stylesheet link though:`<link href="/style.css" rel="stylesheet" type="text/css" media="all">`
As for the favicon, some browsers just download the favicon once and then use that for a long while without noticing when there's a new one. You might see that problem, because you're developing your site and viewing it frequently, but I'd assume most visitors won't because you have your favicon correctly installed!
Do note that this is not the place to discuss this problem because it has nothing to do with the Neocities site's internal code. You can ask these kind of questions on a forum, maybe on neocities itself, or search around/ask a question at https://stackoverflow.com. Have a nice day!

**Comment by minegamer5570** [comment]
I will try the site on a different computer and see what happens... The link script i am using works on all the other sites i help out with.

**Comment by kyledrake** [comment]
Closing since this isn't a Neocities backend issue (which is what this Issues section is for). Looks like you got this figured out regardless.
