### ISSUE TITLE
Allowed File Types Page Doesn't List All Allowed File Types

### ISSUE THREAD

**Issue by Retroity** [neocities/neocities#274]
I just noticed that the page at https://neocities.org/site_files/allowed_types doesn't show all the allowed file types present in listed in [the VALID_EXTENSIONS list](https://github.com/neocities/neocities/blob/master/models/site.rb). The Allowed File Types page should be updated to show all of the file types allowed.

**Comment by jeremyredhead** [comment]
The question is, should it really show _every single one_? 'cause there are a lot (of weird ones).
The other question, is, how do we organize the list? like for example, where does 'xcf' go? (which is basically like a psd file, but for GIMP). I'd gladly look into that tho, have nothing better to do.

(Also, on a separate note, there are several editable file formats not considered editable by the web client, but i should probs just file a separate issue for that)

**Comment by jeremyredhead** [comment]
ok, so by pure chance i came across this which i put together a while ago:
(it's probably out of date and is oddly organized but it's something!)
```
html - html htm 
images - jpg jpeg png gif svg ico webp 
javascript - js json geojson
css - css less sass scss 
text - txt text csv tsv md markdown
xml - xml rss kml 
fonts - eot ttf otf woff woff2 svg
midi - mid midi
3d objects - obj mtl dae 
encrypted - pgp asc
weird - mf pdf key manifest webapp xcf

html htm txt text css js jpg jpeg png gif svg md markdown eot ttf woff woff2 json geojson csv tsv mf ico pdf asc key pgp xml mid midi manifest otf webapp less sass rss kml dae obj mtl scss webp xcf
```

**Comment by ssokolow** [comment]
I'd think that, at minimum, the following makes sense:

1. Add a line saying `eBooks (.epub, .pdf)`
2. Add WebP to the `Image (.jpg, .png, .gif, .svg, .ico)` line
3. Add XCF to the `Image (.jpg, .png, .gif, .svg, .ico)` line. Complex and proprietary though XCFs may be, they're intuitively thought of as images and you've already classified SVGs (which also support layers, groups ,and other fancy things) as images.

**Comment by ssokolow** [comment]
Also, your selection seems a bit odd. 
* You allow ePub and PDF, but not Kindle's MobiPocket (`.mobi`). (The three choices usually offered together when offering eBook downloads.)
* You allow "advanced user" things like 3D objects, CSV, TSV, and GeoJSON which require JavaScript to render in the browser, but not equally browser-unfriendly stuff any user might generate, such as OpenDocument Text (`.odt`), Spreadsheet (`.ods`), and Presentation (`.odp`) files. (OpenDocument is an international standard used as the native format by basically every word processor, spreadsheet tool, and office suite except Microsoft Office, which still supports it as an alternative... and, yes, there does exist a [JavaScript renderer](https://github.com/webodf/WebODF) for OpenDocument.)
* You allow MIDI files, but not Amiga Module formats, which were also common "compact sequenced music requiring a Java applet or [browser plugin](https://openmpt.org/legacy_software)" things in the GeoCities days. (Plus, since Module formats embed their own instrument definitions, they're easier to [play in the browser](https://deskjet.github.io/chiptune2.js/) via JavaScript and give consistent results across all players.)

**Comment by jeremyredhead** [comment]
@Retroity as of commit 9f7bbe16e all valid file extensions are automatically shown on the page (even if it doesn't explain *what* some of those formats are), so I think this issue can be closed.
