### ISSUE TITLE
Location of Doc's?

### ISSUE THREAD

**Issue by Aphris-Karu** [neocities/neocities#321]
I have the site deployed and can see the main page. Are there docs on the setup, admin login, or anything that could help me figure it out?

**Comment by BobK77** [comment]
Because the Issues section on github is for filing problem reports on the code of the neocities system, and working them to closure, and because this question is not relevant to problems with the functioning of the Neocities system, I will close, or recommend closing, this issue as 'not an issue'. 

~~~~~
~~~~~

That being said, I'll offer a few comments, hints, tips on where to go. 

As best I can tell, there are no documents for setup, admin login, and so on for a "deployed site" ... because Neocities is simpler.  

To get a feel for what Neocities is about, read closely the page https://neocities.org/site_files/allowed_types.  In particular, the page says  "Neocities is best with files that are used for making static HTML web sites", and,  "Our goal is to provide you with a free web site so you can arrange content in any way you want."  

A great place to start learning how to use Neocities is the About page, https://neocities.org/about. It includes a link called "Go make your web site!" -- https://neocities.org/#new. 

A great place to learn about building web site -- and presumably how to use Neocities in building your web site -- is the "You can Learn How to Make Websites in The Neocities HTML course", starting from https://neocities.org/tutorials

Some FAQs are found on https://neocities.org/contact

"Settings" are found on https://neocities.org/settings, and each one is explained on its own page/tab. 

The heart of using Neocities to build and modify your website are the functions and features seen on the Dashboard page, https://neocities.org/dashboard :

	Functions and Features on the Dashboard:
	
	Share your site
	List View / Icon View selection
	New File
	New Folder
	Open Folder
	View File
	Manage Folder
	Edit file
	Rename File/Folder
	Delete File/Folder
	Upload
	>> Drag-and-Drop upload is in "Icon View"
	
	At bottom of Dashboard page: 

	Allowed file types
	Download entire site
	Mount your site as a drive on your computer

**Comment by BobK77** [comment]
Recommend Closing this Issue. 

(The question posed by the OP is not relevant to problems with the functioning or design of the Neocities system.  Responses to the question provided in previous comment.)

**Comment by haydenwalker980** [comment]
I know a solution to your admin problem (bump, yes I'm sorry.)

Run this command:
`psql -d neocities`
Then:
```
UPDATE sites
SET is_admin = "t";
```
Finally you can freely access the admin panel.
