### ISSUE TITLE
Backwards compatibility support

### ISSUE THREAD

**Issue by smege1001** [neocities/neocities#329]
This website doesn't provide alternative pages to older browsers

It also doesn't support TLS 1.1/1.0 and SSL 3.0/2.0

**Comment by kyledrake** [comment]
I'm aware of this, and it's expected behavior. Any browsers that don't support our current configuration are obsolete to the point of being unsafe to use. From my experience dealing with issues, users with those specs are more likely to be DDoS attack botnets than legitimate users.

We're really not trying to be "anachronistic" by keeping support for old software. Users probably won't be able to use our front site with those specs anyways, and weakening our crypto would dock the pagerank of our hundreds of thousands of sites just to support a few users. It's just not worth the tradeoffs unfortunately. My recommendation to anyone having this issue is to simply upgrade their browsers to a reasonably new version.
