### ISSUE TITLE
Surf bar does not currently work due to iframe restrictions

### ISSUE THREAD

**Issue by kyledrake** [neocities/neocities#33]
We created this beautiful search capability for sites, but unfortunately it doesn't work on many sites.

The problem is that iframes are now strictly controlled by remote resources, which will prevent browsers from accessing them if they are sourced from an iframe.

There is a possible solution here that I don't yet foresee. The one idea I had in mind was to write some sort of proxy service that filters and processes sites for surf mode, which can then be used in this way. But there are logistical and security issues here I'm not sure I fully understand yet.

More research is needed on this. It would be awesome to bring it back.

Further reading: 
http://stackoverflow.com/questions/7289139/why-are-iframes-considered-dangerous-and-a-security-risk
https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options

**Comment by violasong** [comment]
I feel the surf bar is very important to navigating the social features of the site (visiting a site and then interacting with it is very clunky otherwise). I would suggest raising this in priority to right below the current must-do items for the announcement.

Would this proxy service still be better than injecting the surf bar into the page? I know that feels gross but it just seems so common I have to believe there's a good solution here now.

**Comment by kyledrake** [comment]
Victoria and I talked about this, and we're thinking this should be a high priority, so I'm going to sit down and try to find a way to implement this safely.

**Comment by violasong** [comment]
In addition to Kyle investigating workarounds for this, I will mock up a fallback idea that may be worth implementing initially (surfable user profiles with large screenshots)

**Comment by violasong** [comment]
Done.
