### ISSUE TITLE
Make life harder for SEO spammers

### ISSUE THREAD

**Issue by kyledrake** [neocities/neocities#39]
SEO spam is picking up, and it's only going to get worse. Unless we want to become full-time SEO spam filterers (I know people that work full time at companies doing this - we do NOT want to go down this route), we need to be smarter about preventing this sort of activity on Neocities in order to be efficient.

So I'm introducing two proposed changes to site policy:
- Email addresses will need to be verified before users can be listed on the browse page, since almost all of the SEO sites are created with bad email addresses. This adds a level of technical complexity to the login process that will increase the difficulty of automating this process.
- Sites will require at least two "site changes" across two days before being listed on the browse page.

Not ideal, but when you're small, you need to make concessions like this.

**Comment by violasong** [comment]
Email verification is common enough that I'm ok with inconveniencing users with it. Probably need a little nag dialog at the top of the newsfeed that goes away after successsful validation, with links to resend or change email.

I'd prefer to start with email verification and see how that works before making the browse page restriction, just because the immediacy of the current functionality is pretty cool.

**Comment by kyledrake** [comment]
If you get a chance, could you make a quick nag dialog for me to use for this? That would be great. Thank you!

**Comment by violasong** [comment]
I was trying to decide if it should be a separate box or if it could be somehow incorporated into the green welcome boxes. Here's how it could look separately:

![screen shot 2015-02-01 at 9 13 02 pm](https://cloud.githubusercontent.com/assets/55994/5995384/415ed55c-aa57-11e4-9c29-4ab48a3030d1.png)

On the dashboard, the welcome dialog has a line saying "Make some changes and weʼll add your website to our website gallery!" so maybe that part just needs a line about "and make sure to verify your email"

Most sites also allow you to enter a code from the email to verify you got it (maybe because of really old email clients that don't have link support?) but I don't know if that's necessary for us.

Would email validation remove the need to require site edits over two days to unlock commenting privileges, or did you want that restriction either way?

**Comment by violasong** [comment]
I just noticed your commit, "minimum 100 views for browse to reduce noise." If that's in place we'll have to modify the dashboard welcome dialog to mention it. What kind of noise were you seeing?
