### ISSUE TITLE
/site/name.rss noncompliant

### ISSUE THREAD

**Issue by annahla** [neocities/neocities#458]
each entry in an rss feed must have a unique ID, and neocities' autogenerated rss feed uses the same ID for each, making either one or no entries show up in a feed reader.

**Comment by riomccloud** [comment]
+1. All the Neocities RSS/Atom feeds don't work properly since they have the same ID. The feeds are not validated by W3C. Since the majority of sites do not offer feeds, it's hard to keep track of the updates. :/

**Comment by kyledrake** [comment]
I'm working on this today. What are the most popular RSS feed readers right now so I can use them for testing?

**Comment by kyledrake** [comment]
Okay I have "got it working again" for site updates. I switched to RSS 2 from Atom but it shoudn't matter implementation wise. I also added a site screenshot so that it looks nicer with some RSS readers.
https://github.com/neocities/neocities/commit/f261db16b0bdbc74bd60ede9ee1b518b090ed069

It only tracks site updates at the moment, and I'm not sure if that's good enough or if more "events" should be added, but if it started updating each time a comment was posted for example, things could potentially get pretty spammy. I'm open to suggestions for adding things here, and also let me know if you're still seeing issues with RSS feeds after this.

**Comment by riomccloud** [comment]
Seems to be working fine now. Thanks!

> It only tracks site updates at the moment, and I'm not sure if that's good enough or if more "events" should be added, but if it started updating each time a comment was posted for example, things could potentially get pretty spammy.

I think the ideal would be to include the site owner's own text posts in the feed, if it doesn't overload the server. I and several other users use this as a changelog for our sites. However, if that's not possible, the way it's working now is already good. :)

**Comment by kyledrake** [comment]
The way it's setup is it links to event id, so if you add the comment on changes to the site update event, it should appear in their rss reader when it loads the page. I'm not sure what the best way to express this ux to people is though.
