### ISSUE TITLE
multiple sites getting shadowbanned because of "jerk filter"

### ISSUE THREAD

**Issue by pinkvampyr** [neocities/neocities#467]
So, today I logged onto Neocities to find that I was unable to comment on any profiles or posts unless the user followed me back. I know about this "jerk filter" that kicks in when someone gets blocked by 4 or more people, because several other people I know were also shadowbanned. None of us post hate speech or harass other users, so I don't really understand why we should be prevented from interacting with others. I would appreciate if you reconsidered or reworked the "jerk filter" to prevent users that aren't causing harm from being dealt the same hand as those who are, because at least 4 people weren't a fan of someone. My neocities un is pinkvampyr, if that helps. I'll be reaching out to support about my situation as well but I hope that you'll consider dealing with this situation on a larger scale.

**Comment by sweatshirts** [comment]
it is generally stupid that  "jerk filter" is set to 4. it's enough to not vibe with **one** **_singual_** person. they can make alt accounts to block you from those alt accounts, and you're a goner.

this needs to be revised

**Comment by xandracc** [comment]
this does appear to be an issue that hasn't been touched since 2019, and i think another look at the jerk filter is warranted, IMO. the site has exploded since then, and there's more opportunities for this to be abused or even brigade others with. seems like this could be reworked to increase over time with each additional block versus an outright shadowban at 4 users.

not to conflate this issue with blocking as a whole, but if there's an opportunity to also look at unblocking folks (for accidental blocks), this might be a good time to revamp how the blocking system works, especially if it's erroneously shadowbanning non-offending users.

**Comment by PunkWasp** [comment]
I've been shadowbanned as well due to this, my username on Neocities is punkwasp. I also know I personally block people just due to not wanting to interact with them more often than I block them due to harassment or similar things. I wouldn't want someone who's not necessarily doing anything wrong to get shadowbanned just because I'm trying to curate my online experience.

**Comment by AzureBede** [comment]
I've been shadowbanned too, and it's such a pain. I just want to comment on people's sites and tell them that I like the stuff they do... That's the whole point of the social aspect of the site! To inspire each other and socialize and stuff! I just block people I find annoying all the time; it doesn't necessarily mean that someone is harassing others if they're blocked a lot.

**Comment by kyledrake** [comment]
I upped it to 25. If people are still getting blocked at that point and are not infact jerks, I'll up it again and/or start banning accounts brigade blocking people maliciously.

**Comment by hf02** [comment]
> I upped it to 25. If people are still getting blocked at that point and are not infact jerks, I'll up it again and/or start banning accounts brigade blocking people maliciously.

as an idea, maybe consider splitting the button. like into a "mute" button and a "block as jerk" button? as some have mentioned above, people block just to curate a feed, not to avoid a jerk.
