### ISSUE TITLE
Email Confirmation Not Working - Multiple Reports on Reddit

### ISSUE THREAD

**Issue by miguelzinh3** [neocities/neocities#480]
I am writing to report an issue that seems to be affecting a number of users, including myself, regarding email confirmation. 

**Issue Description:**
The email confirmation process does not appear to be working as intended. After signing up or performing actions that require email verification, the confirmation email is either not received or does not function correctly.

**Evidence of the Issue:**
This problem has been discussed extensively on Reddit, indicating that it is a widespread issue. Here are a couple of threads where users are sharing their experiences:
1. [Email Verification Issue](https://www.reddit.com/r/neocities/comments/18ytwsi/email_verification_issue/)
2. [Issue with Not Receiving Confirmation Email](https://www.reddit.com/r/neocities/comments/18ydjkw/has_anyone_been_able_to_solve_the_issue_with_not/)

**Impact of the Issue:**
This issue is hindering the user experience, as it prevents new users from fully engaging with the platform and may affect the perception of reliability and user-friendliness of NeoCities.

**Request for Action:**
I kindly request the team to investigate this issue. Any updates or workarounds would be greatly appreciated by the community.

**Comment by kyledrake** [comment]
Looking into it now

**Comment by kyledrake** [comment]
I figured this out - TLDR it was an issue with a mail server after a switch to a new nameserver (it didn't switch to the new DNS resolver and just stopped working). And of course, I didn't see this because the emails that would have reported it also weren't working. All of the pending mail should have been sent out, including pending confirmation emails. Apologies for the issues on this and thanks for letting me know!
