### ISSUE TITLE
Make the Content Security Policy for new accounts less aggressive

### ISSUE THREAD

**Issue by hf02** [neocities/neocities#484]
It seems that recently created accounts have a different and more restrictive Content Security Policy. [As someone has encountered on Reddit](https://redd.it/197cn3j), this breaks [Cusdis](https://cusdis.com/).

Here's the policy [on an account I just made](https://content-security-policy.neocities.org/):

```
content-security-policy: upgrade-insecure-requests; default-src * 'unsafe-inline' 'unsafe-eval' data: blob:; connect-src 'self'; form-action 'self'; img-src * data:; script-src * 'unsafe-inline' 'unsafe-eval'; style-src * 'unsafe-inline'; font-src * data:; object-src *; media-src *; frame-src *;
```

And [on my ~3 year old account](https://dabric.neocities.org/):
```
content-security-policy: upgrade-insecure-requests; default-src 'unsafe-inline' 'unsafe-eval' 'self' data: blob: *
```

**Comment by kyledrake** [comment]
I'm sorry but this is going to be a wontfix. We've had way too much abuse from allowing it, exceeding far more than the legitimate use cases, and we aren't supporting after-load connect-src from new free sites going forward. I've changed the plan info recently to reflect that this is going to be a supporter plan feature from here on out.

I suppose that a whitelist of connect-src sites could be made for CDNs and certain third party services, but that could end up getting long quick, and I'm not sure what the best way to do that would be.

**Comment by 8bitKittyKat** [comment]
@kyledrake I know this issue is a **wontfix**, and can understand why, but I ran into problems with the security policy when all I wanted to do was use a javascript MIDI player to play MIDI music in the background of my Neocities page, as one would expect of the average user's Geocities-era page. MIDI files are even a supported upload file type for Neocities but they serve no purpose without a way to play them.

Personally I would like it if Neocities had backend support for emulating MIDI playback so that a simple `<embed>` or `<bgsound>` tag would work like in the old days when I had a Geocities page, using something like [bg-sound](https://github.com/feross/bg-sound), but could you perhaps at least add the required external data URLs for [MIDIjs](http://www.midijs.net/) to a whitelist for the CSP?

I was getting `“connect-src 'self' blob:”` errors for multiple MIDI patch files the script was trying to load from https://cdn.scorio.com/midijs/

There are other javascript synthesizers such as [webaudio-tinysynth](https://github.com/g200kg/webaudio-tinysynth) but [MIDIjs ](http://www.midijs.net/)was just the first one I found.

Thank you.

**Comment by kyledrake** [comment]
@8bitKittyKat If you include code to play midi files on your site on Neocities, it should have no trouble loading the midi files if they are also being loaded from your site, or any other location on Neocities. If that is not the case, I want to try to fix it, but it has to be an example using code placed on a Neocities site.

Another way to think about this design change is that it makes all of the sites built on Neocities far more robust and increases their longevity, because if the third party resource you are using goes down or stops working, it will break functionality of your site. To illustrate that point well, the midi site you linked is not working because the midi files it references are now producing broken link 404 errors. That source has clearly fallen into disrepair and any sites that depend on it will probably break soon too. I would recommend looking at https://github.com/feross/timidity, which I've used in the past to emulate MIDI files with great success.

FWIW, this was not a fun decision for me to make. But too many criminals are abusing this functionality for malicious activity, and like most other platforms right now (how many sites let you login without your phone now?), we also need to circle the wagons; It's dangerous to the future of the site and the search rankings of our legitimate sites, and it's not compatible with our core mission to bring back individuals making fun, creative static HTML sites.

**Comment by 8bitKittyKat** [comment]
@kyledrake Ah, sorry, there seems to be some misunderstanding.  The MIDI files I'm using are in fact hosted on my Neocities site.  I never tried to use any hosted elsewhere.  The issue is the MIDI emulators (including [feross/timidity](https://github.com/feross/timidity), as you linked) use libraries and instrument patch files that can't be installed or hosted to a personal Neocities page, unless I'm missing something here.  I run into issues when I try to use any of them.  The first step of [feross/timidity](https://github.com/feross/timidity) says to run `npm install timidity` and I'm fairly certain that's not possible on the user side.  Manually copying the instrument patch files from `Drum_000` and `Tone_000` and `libtimidity.wasm` is also denied because they are not allowed filetypes.

To demonstrate as you asked, and using [feross/timidity](https://github.com/feross/timidity) as you've linked, I've added the script from the instructions and pointed it to a MIDI file hosted on a test page at my Neocities site, but it won't work because of the missing requirements.  The error is different than the other library I was using, but the result is the same.

https://8bitkittykat.neocities.org/_test/
You'll have to click `Enter` because the script I inserted is on a page inside of a frame that doesn't render correctly on its own because of the styling I've used.

The page in the frame is [here](https://8bitkittykat.neocities.org/_test/home.html) if you want to just view the source.

And I completely understand wanting to keep Neocities secure, and appreciate its existence FWIW.  Thanks for your time with my particular issue.

**Comment by 8bitKittyKat** [comment]
I have attempted to use the [feross/bg-sound](https://github.com/feross/bg-sound) package which is better aimed at my needs, and is linked in the readme of [feross/timidity](https://github.com/feross/timidity) and suggested for anyone looking for a simpler way to use what the timidity package offers.  However, this runs me into the same problem I was initially running into with the CSP.

`Content-Security-Policy: The page’s settings blocked the loading of a resource (connect-src) at https://bitmidi.com/timidity/libtimidity.wasm because it violates the following directive: “connect-src 'self' blob:”`

I've updated my test site from above [here](https://8bitkittykat.neocities.org/_test/).  The page on my site where the MIDI script is loaded is [here](https://8bitkittykat.neocities.org/_test/home).

There doesn't seem to be an easy way to play MIDI on Neocities now that I can figure out.  I've seen other sites on Neocities, [this one](https://zumi.neocities.org/stuff/midi/) for example, that are able to do it but if I replicate what they're doing I run into issues with CSP again.

**Comment by kyledrake** [comment]
Just an update that I'm planning to work on this and make it so you can do midi support on your site but no ETA yet, stay tuned.

**Comment by 8bitKittyKat** [comment]
@kyledrake Hey, I really appreciate you doing that. Thanks!

**Comment by Pigamer37** [comment]
Hi! I'm kind of new in terms of web developement, and I understand this is still wontfix. I will comment just in case I can get a solution.

I'm developing a port of a Computer Vision tool based on OpenCV ([https://kbs-lucas.neocities.org/tools/Lane-Detector]
(https://kbs-lucas.neocities.org/tools/Lane-Detector)). Right now it works using the user's webcam, although OpenCV.js throws some CSP errors because it tries to load some data: URI's externally, but they don't seem important because the scripts works.

The real problem is that, now that I'm trying to implement an alternative to use an `<input type="file">` tag to get a file instead of the camera feed, whenever I'm trying to use it it throws an error, I'll copy it:
```
Refused to load media from 'blob:https://kbs-lucas.neocities.org/[random numbers that point to the file]' because it violates the following Content Security Policy directive: "media-src *". Note that '*' matches only URLs with network schemes ('http', 'https', 'ws', 'wss'), or URLs whose scheme matches `self`'s scheme. The scheme 'blob:' must be added explicitly.
``` 
As I said before, I'm new to this, but it seems strange. I understand it's a blob: and thus not explicitly included in the policy. I've tried loading it as data: but same thing (different error, but similar). Seems weird that I can get access to camera feeds but not to files users specified themselves. Maybe there's another way I can get around this? Just to clarify, everything happens client-side, of course.

Thanks in advance!

**Comment by kyledrake** [comment]
@Pigamer37 I think I have a fix for this, try it now.

**Comment by Pigamer37** [comment]
@kyledrake Just tried, same error.
![image](https://github.com/user-attachments/assets/05eee394-b6ee-481c-b130-7fa831468ce5)

**Comment by ForeskinJim** [comment]
Just open up whatever video editor, add in whatever audio you want, upload said video to youtube and embed it in a 1x1px player with ?autoplay=1 after the video ID. Audio will autoplay so long as the user/browser has allowed autoplaying from youtube/your website. You can use Keppy's MIDI Converter to render any MIDI in whatever sound found you want.

I've been doing this for years to add annoying background music to boards and blogs that support embedding HTML into your posts. It's also how I've added BGM to my [omg.lol](weed.omg.lol) site. Something like this:

`<iframe src="https://www.youtube.com/embed/_AWl4JdZzmI?autoplay=1" width="1" height="1" title="BGM" frameborder="0" allowfullscreen></iframe>`

**Comment by shodanwashere** [comment]
I'm having a reverse problem to what @hf02 was having where my page used to be able to display iframes correctly, but all of a sudden, starting today, they no longer do because i'm assuming my iframe CSP was changed to what is normal for fairly recent accounts (`frame-src *`) to a new one that restricts it only to websites within neocities (`frame-src 'self' https://*.neocities.org`). Is this normal behavior?

Website in question: https://shodantltwb.neocities.org

<img width="1680" height="818" alt="Image" src="https://github.com/user-attachments/assets/b3d59398-3456-46dd-9621-b43518872bf6" />

**Comment by kyledrake** [comment]
@shodanwashere This was a mistake I introduced into our CDN last night, it has been reverted and resolved as of this morning. It's not going to be part of the CSP sandbox.

**Comment by rubensoleao** [comment]
Can we also allow google translate?


I can't use it on my neocities website. It's a very usefull tool for doing easy translations. 

```
Request URL
https://translate-pa.googleapis.com/v1/translateHtml
Referrer Policy
strict-origin-when-cross-origin
```
