### ISSUE TITLE
Unable to delete a directory named x.html

### ISSUE THREAD

**Issue by kugland** [neocities/neocities#494]
It’s not possible to delete a directory named “x.html” neither in the web interface nor with the API. Even after I renamed it (removing the problematic extension), I cannot delete it.

**Comment by kyledrake** [comment]
I wasn't able to reproduce this, how were you able to delete the file? Or is it on a different site?

**Comment by kugland** [comment]
Hello!

It’s on kugland.neocities.org.

I used the API to create a directory named x.html (while writing a tool to
deploy sites), then I tried to delete it,
also using the API, but I wasn't able to do it. I was able to rename it to
another name (I don't remember which),
through the web interface, but even after renaming it, I couldn't remove it
either through the API or through
the web interface. Then I renamed it to ".ignore", and I'm still unable to
remove it through the API (it doesn't
show in the web interface now, but it's there when I call /api/list).

By the way, check out the tool I made for deploying to NeoCities.

https://github.com/kugland/neocities-deploy – the CLI tool

https://github.com/kugland/neocities-client – the Rust library I made for it

If you can add it to the page https://neocities.org/api, that would be
great!

Thanks,
André Kugland

**Comment by kyledrake** [comment]
Took care of it with your file.

This is actually an issue with our uploader I've been trying to figure out for a while, one in a very few file uploads gets in some sort of error state and fails to upload the file correctly. If you can repro with an x.html directory let me know, but my guess is if you try to do it again it won't do the same thing. Apologies for the issue here.

**Comment by kugland** [comment]
Thanks!
