### ISSUE TITLE
Updating the design of Neocities

### ISSUE THREAD

**Issue by M-Valentino** [neocities/neocities#496]
So the design of Neocities hasn't been updated in 10 years. Based on the content people mostly share on Neocities, you might think this is fitting, but mid 2010 design isn't yet considered nostalgic and cool because its too recent. Having a design that doesn't look up to date might turn people away because it may appear less secure or its not the latest and greatest technology.

I feel like an easy way to update the design a little bit is to remove the gradient on buttons and make them more square like the Material UI buttons. Another easy update would be to replace the cream colored backgrounds with white colored backgrounds.

**Comment by erikhoudini** [comment]
Dark mode would be a good compromise between a design overhaul and leaving it the same.

**Comment by kyledrake** [comment]
I've pondered a re-design bu in practice it's not a good decision for now. Besides just liking the current design, re-designing it would be a massive undertaking and would take away resources from other more important things at the moment. I feel like the design has accidentally improved over time as other sites have switched to more frontend JS heavy designs, with slow loading and lots of "please wait" spinner. Also if I redesign the site, just as many people will complain about the redesign as like the new one, if not more.

Dark mode would be cool, but I think I would rather steer users towards browser plugins like Dark Reader that already do this really well. It may make sense to make a non-extension "dark mode", but I would want that to be a really specific task to be done.

I'm going to close this issue because this isn't really an "issue" with the code and I don't want to keep "open ended" issues around, but if anyone was interested in doing design work and issuing pull requests with css changes, I would entertain PRs related to improving the design.
