### ISSUE TITLE
Consider getting neocities.org labeled as an eTLD.

### ISSUE THREAD

**Issue by JasonTable** [neocities/neocities#513]
This page explains it better than I can but it would basically make it so the subdomains are treated as separate sites. Github, for example, uses it for their github static sites.
https://developer.mozilla.org/en-US/docs/Glossary/eTLD
https://publicsuffix.org/

**Comment by kyledrake** [comment]
Unfortunately it's been told that the cookies would not work. There's a
whole crazy active thread I'm responsible for in the PSL mailing list if
you want to read more.

A possible solution is to use www but I deeply prefer to keep the root site
on neocities.org and keep the subdomains as the sites and I think it's
easier for people to understand.

**Comment by kyledrake** [comment]
Going to close this. We may do PSL but it's up in the air at this point, don't want to keep it as an issue. FWIW, not being on the PSL doesn't mean sites don't get treated as the same, cookies are still contained to the root and sub domains. Whether the subdomains are treated differently is more related to corporate policies rather than entries on the PSL. I've had engineers at the browser companies not be able to describe to me the way they use PSL (they claimed cookies wouldn't work and they worked so..).
