### ISSUE TITLE
Better consistency

### ISSUE THREAD

**Issue by violasong** [neocities/neocities#84]
- If we're using the single word "Websites" in the navigation, we should probably also use that everywhere else instead of "web sites"
- Websites link should ideally be /websites, with /browse still redirecting there
- Support Us link should ideally be /supportus, with /plan redirecting there

**Comment by colbyrussell** [comment]
> Support Us link should ideally be /supportus, with /plan redirecting there

/pricing is a pretty popular way to do this.  I've certainly tried visiting neocities.org/pricing more than a few times both before and after signing up, especially for comparing plans.  The "Upgrade to Supporter" / "Support Us" link in the top bar struck me as a pretty unintuitive place to get at the facts—being the third or fourth place I looked.

Eventually after training myself about this charitable messaging, I still ended up missing these "support" links, because I'd scroll down to the footer, hit the "Donate" link, and then backtrace.
